name: Temp Sajt
favicon: null
layout_spectrum: 0.451804225333035
typography_spectrum: 0.56534
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7789465403184295
  lightness: 0.8807842675596476
  saturation: 0.7664289474487305
  rhythmicContrast: 0.01004381338134408
purpose: []
